import Link from 'next/link';
import MindxLogo from './mindx-logo';
import './home.css';
import WorkspaceArt from './home-workspace-art';

const spaces=[
 {id:'studio',number:'01',title:'Make it move.',name:'Studio',tag:'REAL ROBOT',description:'Turn blocks into action. Write your program and connect your VEX GO robot.',action:'Open Studio',symbol:'⌘'},
 {id:'training',number:'02',title:'Find your own way.',name:'Training',tag:'VIRTUAL FIELDS',description:'Navigate a maze, move a block and solve a mission. No physical robot needed.',action:'Explore missions',symbol:'↗'},
 {id:'quiz',number:'03',title:'Put ideas to the test.',name:'Quiz & Homework',tag:'LEARN & PRACTICE',description:'Explore lessons, read real code blocks and check what you have learned.',action:'Start learning',symbol:'?'},
 {id:'classroom',number:'04',title:'Grow together.',name:'Classroom',tag:'FOR YOUR CLASS',description:'Celebrate skills, collect points and give every learner a character of their own.',action:'Open Classroom',symbol:'✳'},
];
function Playground(){return <div className="hub-playground" aria-label="Illustration of a robot navigating a virtual field" role="img"><div className="playground-top"><span><i/> ROBOTICS PLAYGROUND</span><span>FIELD / 01</span></div><svg viewBox="0 0 560 390" aria-hidden="true"><defs><pattern id="home-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#dddccf" strokeWidth="1"/></pattern></defs><rect x="20" y="10" width="520" height="355" rx="16" fill="#f9f7ee"/><rect x="20" y="10" width="520" height="355" rx="16" fill="url(#home-grid)"/><path d="M105 292H225V130H433V78" fill="none" stroke="#df453d" strokeWidth="5" strokeDasharray="10 9"/><rect x="295" y="204" width="135" height="38" rx="7" fill="#263b3b"/><rect x="294" y="194" width="135" height="38" rx="7" fill="#45615e"/><rect x="100" y="66" width="46" height="46" rx="9" fill="#e8b54b"/><rect x="106" y="60" width="46" height="46" rx="9" fill="#ffd16b"/><circle cx="433" cy="70" r="29" fill="#c9dc9e"/><path d="m420 70 9 9 18-20" stroke="#365646" strokeWidth="4" fill="none" strokeLinecap="round"/><circle cx="105" cy="290" r="47" fill="#d7e9f3"/><image href="/training-robot.png" x="68" y="253" width="74" height="74"/><text x="74" y="348" fontSize="10" letterSpacing="2" fill="#56716c">START HERE</text></svg><div className="playground-code"><span className="code-hat">when started</span><span>drive forward <b>200</b> mm</span><span>turn right <b>90</b> degrees</span></div><div className="playground-note"><span>↳</span> A little code.<br/>A world of possibilities.</div></div>}
export default function Home(){return <main className="home-hub"><a className="hub-skip" href="#workspaces">Skip to workspaces</a><header className="hub-nav"><Link href="/" aria-label="mindX home"><MindxLogo/></Link><span className="hub-nav-label">ROBOTICS LAB</span><nav aria-label="Main navigation"><Link href="/studio">Studio</Link><Link href="/training">Training</Link><Link href="/quiz">Quiz</Link><Link href="/classroom">Classroom</Link></nav><Link className="hub-nav-start" href="/training">Let’s explore <span>↗</span></Link></header>
<section className="hub-hero"><div className="hub-hero-copy"><span className="hub-eyebrow"><i/> BIG IDEAS START SMALL</span><h1>Think it.<br/>Code it.<br/><em>Bring it to life.</em></h1><p>A playground for curious minds. Build with code, explore robot missions and discover what you can do next.</p><div className="hub-hero-actions"><Link className="hub-button" href="/training">Start exploring <span>↗</span></Link><Link className="hub-text-link" href="/studio">I have a robot <span>→</span></Link></div><div className="hub-hero-foot"><span className="hub-mini-icon">↗</span><span>Start with a virtual mission.<br/><b>Just your browser and a little curiosity.</b></span></div></div><Playground/></section>
<section id="workspaces" className="hub-spaces"><div className="hub-section-heading"><div><span className="hub-eyebrow">YOUR NEXT ADVENTURE</span><h2>One lab. Four ways to grow.</h2></div><p>Choose where you want to begin.</p></div><div className="hub-space-grid">{spaces.map(space=><Link key={space.id} href={'/'+space.id} className={'hub-space hub-space-'+space.id}><div className="hub-space-top"><span>{space.number} / {space.tag}</span><span className="hub-space-symbol" aria-hidden="true">{space.symbol}</span></div><WorkspaceArt kind={space.id}/><span className="hub-space-name">{space.name}</span><h3>{space.title}</h3><p>{space.description}</p><span className="hub-space-action">{space.action}<span>↗</span></span></Link>)}</div></section>
<section className="hub-create"><div className="hub-create-art" aria-hidden="true"><span>+</span><span>□</span><span>○</span><span>↗</span></div><div><span className="hub-eyebrow">A BLANK FIELD. YOUR RULES.</span><h2>Dream up the next challenge.</h2><p>Add your own background, arrange obstacles and build a field worth exploring.</p></div><Link href="/training/custom?new=1">Create a field <span>↗</span></Link></section><footer className="hub-footer"><span>mindX <b>·</b> Robotics Lab</span><p>Made for the next generation of makers.</p><a href="#workspaces">Find your workspace ↑</a></footer></main>}
