import MindxLogo from './mindx-logo';
import Link from 'next/link';
import './home.css';

export default function Home() {
 return <main className="home-hub">
  <header className="hub-nav"><Link href="/" className="brand official-brand"><MindxLogo/></Link><nav aria-label="Main navigation"><Link href="/studio">Studio</Link><Link href="/training">Training</Link><Link href="/classroom">Classroom</Link></nav></header>
  <section className="hub-intro"><span className="hub-eyebrow">ONE COMMUNITY. MANY WAYS TO GROW.</span><h1>Where will your<br/><em>next idea go?</em></h1><p>Program a real robot or explore a virtual field.<br/>Choose your workspace and start creating.</p></section>
  <section className="hub-workspaces" aria-label="Choose your workspace">
   <Link href="/studio" className="workspace-card workspace-studio"><div className="workspace-top"><span>01 / REAL ROBOT</span><span className="workspace-badge">VEX GO</span></div><div className="workspace-art studio-art" aria-hidden="true"><div className="hub-code"><span>when started</span><span>drive forward <b>200</b> mm</span><span>turn right <b>90</b> degrees</span></div><svg viewBox="0 0 160 160"><rect x="14" y="48" width="25" height="77" rx="9" fill="#a5c3b4"/><rect x="121" y="48" width="25" height="77" rx="9" fill="#a5c3b4"/><rect x="30" y="22" width="100" height="123" rx="27" fill="#c8ee78"/><rect x="44" y="48" width="72" height="39" rx="12" fill="#173b34"/><path d="M62 61v12m36-12v12" stroke="#c8ee78" strokeWidth="8" strokeLinecap="round"/><path d="M64 111h32" stroke="#173b34" strokeWidth="6" strokeLinecap="round"/></svg></div><h2>Studio</h2><p>Build your code. Connect your VEX GO.<br/>Bring your ideas into the real world.</p><div className="workspace-tags"><span>Block coding</span><span>Robot connection</span></div><div className="workspace-cta">Open Studio <span>↗</span></div></Link>
   <Link href="/training" className="workspace-card workspace-training"><div className="workspace-top"><span>02 / VIRTUAL ROBOT</span><span className="workspace-badge">NO ROBOT NEEDED</span></div><div className="workspace-art field-art" aria-hidden="true"><svg viewBox="0 0 460 170"><rect x="30" y="15" width="400" height="140" rx="12" fill="#e4eddb" stroke="#c4d4b6"/><path d="M60 125h100V50h125v75h105" fill="none" stroke="#83a268" strokeWidth="3" strokeDasharray="7 7"/><rect x="208" y="85" width="45" height="55" rx="5" fill="#496556"/><rect x="308" y="33" width="29" height="29" rx="4" fill="#e4aa55"/><circle cx="389" cy="125" r="20" fill="#b2d47e" stroke="#668c4e" strokeWidth="2"/><path d="m380 125 6 6 12-13" fill="none" stroke="#426531" strokeWidth="3"/><circle cx="65" cy="125" r="22" fill="#173b34"/><path d="m65 112-8 20h16z" fill="#d3edb5"/></svg></div><h2>Training</h2><p>Choose a mission. Solve the virtual field.<br/>Practice, experiment and try again.</p><div className="workspace-tags"><span>Practice missions</span><span>Custom fields</span></div><div className="workspace-cta">Explore Training <span>↗</span></div></Link>
  </section>
  <section className="hub-custom"><div><span className="hub-eyebrow">CELEBRATE EVERY LEARNER</span><h2>Your class. Growing together.</h2><p>Give points, customize companions and celebrate progress with classroom rewards.</p></div><Link href="/classroom">Open Classroom <span>↗</span></Link></section>
  <section className="hub-custom"><div><span className="hub-eyebrow">MAKE IT YOUR OWN</span><h2>Your field. Your challenge.</h2><p>Upload a background, place obstacles and design a new robot mission.</p></div><Link href="/training/custom?new=1">Create a field <span>↗</span></Link></section>
  <footer className="hub-footer"><span>mindX Robotics Lab · VEX GO</span><span>Studio connects to a compatible robot. Training runs virtually.</span></footer>
 </main>;
}

