
declare module Blockly.blockRendering {

    interface IPathObject {
    }

    class PathObject extends PathObject__Class { }
    /** Fake class which should be extended to avoid inheriting static properties */
    class PathObject__Class implements Blockly.blockRendering.IPathObject  { 
    
            /**
             * An object that handles creating and setting each of the SVG elements
             * used by the renderer.
             * @param {!SVGElement} root The root SVG element.
             * @constructor
             * @implements {Blockly.blockRendering.IPathObject}
             * @package
             */
            constructor(root: SVGElement);
    
            /**
             * The primary path of the block.
             * @type {SVGElement}
             * @package
             */
            svgPath: SVGElement;
    
            /**
             * The light path of the block.
             * @type {SVGElement}
             * @package
             */
            svgPathLight: SVGElement;
    
            /**
             * The dark path of the block.
             * @type {SVGElement}
             * @package
             */
            svgPathDark: SVGElement;
    
            /**
             * Set the path generated by the renderer onto the respective SVG element.
             * @param {string} pathString The path.
             * @package
             */
            setPaths(pathString: string): void;
    
            /**
             * Flip the SVG paths in RTL.
             * @package
             */
            flipRTL(): void;
    } 
    
}
